import type { Task } from "@/types";

export const mockTasks: Task[] = [
  {
    id: "task-1",
    title: "Design the new landing page",
    project: "Website Redesign",
    status: "todo",
    priority: "high",
    dueDate: new Date(new Date().setDate(new Date().getDate() + 3)),
    description: "Create a modern and responsive design for the new landing page using Figma.",
  },
  {
    id: "task-2",
    title: "Develop the API for user authentication",
    project: "Backend",
    status: "inprogress",
    priority: "high",
    description: "Implement JWT-based authentication for the user API.",
  },
  {
    id: "task-3",
    title: "Write documentation for the API",
    project: "Backend",
    status: "todo",
    priority: "medium",
    dueDate: new Date(new Date().setDate(new Date().getDate() + 7)),
  },
  {
    id: "task-4",
    title: "Fix bug in the payment gateway integration",
    project: "Mobile App",
    status: "done",
    priority: "high",
    description: "The payment gateway is failing for some credit cards. Investigate and resolve.",
  },
  {
    id: "task-5",
    title: "Plan Q3 marketing campaign",
    project: "Marketing",
    status: "todo",
    priority: "medium",
    dueDate: new Date(new Date().setDate(new Date().getDate() + 10)),
  },
  {
    id: "task-6",
    title: "Morning run - 5km",
    project: "Fitness",
    status: "done",
    priority: "low",
  },
  {
    id: "task-7",
    title: "Read 'Atomic Habits'",
    project: "Personal Growth",
    status: "inprogress",
    priority: "low",
    description: "Read one chapter every day.",
  },
  {
    id: "task-8",
    title: "Setup CI/CD pipeline",
    project: "DevOps",
    status: "inprogress",
    priority: "high",
    dueDate: new Date(new Date().setDate(new Date().getDate() + 4)),
  },
  {
    id: "task-9",
    title: "Review pull requests",
    project: "Website Redesign",
    status: "done",
    priority: "medium",
  },
  {
    id: "task-10",
    title: "Learn Next.js Server Components",
    project: "Education",
    status: "todo",
    priority: "medium",
  },
];
